import { Inter } from "next/font/google";


import { ChakraProvider } from "@chakra-ui/react";
import NavBar from "./component/NavBar";
import HeroSection from "./component/HeroSection";
import Packages from "./component/PackageSectoin";
import BookingCard from "./component/booking.sheet";
import Footer from "./component/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ChakraProvider>
        <NavBar />
        <HeroSection />
        <BookingCard/>
        <body>{children}</body>
        <Footer/>
      </ChakraProvider>
     

    </html>
  );
}
